# Generated by Django 2.2.28 on 2023-04-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230413_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user_type',
        ),
    ]
