# Generated by Django 2.2.28 on 2023-04-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_client_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client',
        ),
    ]
