# Generated by Django 2.2.28 on 2023-04-13 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_client_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('superuser', 'Super User'), ('admin', 'Admin'), ('client', 'Client'), ('coach', 'Coach'), ('coachee', 'Coachee')], default='superuser', max_length=10),
        ),
    ]
