# Generated by Django 2.2.28 on 2023-04-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'List of all client'},
        ),
    ]
